language: objective-c
osx_image: xcode8.3

branches:
  only:
  - test/detox

env:
  global:
  - NODE_VERSION=stable

install:
- brew tap facebook/fb
- export CODE_SIGNING_REQUIRED=NO
- brew install fbsimctl --HEAD

- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION

- npm install -g react-native-cli
- npm install -g detox-cli

script:
- npm install
- cd e2eTests
- npm install
- detox build --configuration ios.sim.release
- detox test --configuration ios.sim.release --cleanup
